accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import (signup)

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('receipts/', include('receipts.urls')),
    path("", RedirectView.as_view(url=reverse_lazy("receipt_list")), name="home"),
]

    # path("accounts/login/", LoginView.as_view(), name="login"),
    # path("accounts/logout/", LogoutView.as_view(), name="logout"),

receipts/urls.py
from django.urls import path

from receipts.views import (
  ReceiptsListView,
  ReceiptsCreateView,
  AccountsListView,
  AccountsCreateView,
  CategoriesListView,
  CategoriesCreateView,
)


urlpatterns = [
  path('', ReceiptsListView.as_view(), name='receipt_list'),
  path('create/', ReceiptsCreateView.as_view(), name='receipt_create'),
  path('accounts/', AccountsListView.as_view(), name='accounts_list'),
  path('accounts/create/', AccountsCreateView.as_view(), name='accounts_create'),
  path('expense_categories/', CategoriesListView.as_view(), name='expense_categories_list'),
  path('expense_categories/create/', CategoriesCreateView.as_view(), name='expense_categories_create'),
]

receipts/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class Receipts(models.Model):
  vendor = models.CharField(max_length=100)
  total = models.DecimalField(decimal_places=2, max_digits=12)
  tax = models.DecimalField(decimal_places=3, max_digits=12)
  date = models.DateTimeField()
  category = models.ForeignKey(
    'Categories',
    related_name="receipts",
    on_delete=models.CASCADE,
    null=True
    )
  account = models.ForeignKey(
    "Accounts",
    null=True,
    related_name="receipts",
    on_delete=models.CASCADE,
    )
  purchaser = models.ForeignKey(
    settings.AUTH_USER_MODEL,
    related_name="receipts",
    on_delete=models.CASCADE,
    null=True
    )



  def __str__(self):
      return self.name


class Accounts(models.Model):
  name = models.CharField(max_length=100)
  number = models.PositiveIntegerField()
  owner = models.ForeignKey(
    settings.AUTH_USER_MODEL,
    related_name="accounts",
    on_delete=models.CASCADE,
    null=True
    )


  def __str__(self):
      return self.name


class Categories(models.Model):
  name = models.CharField(max_length=100)
  owner = models.ForeignKey(
    settings.AUTH_USER_MODEL,
    related_name="categories",
    on_delete=models.CASCADE,
    null=True
  )

  def __str__(self):
      return self.name


# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
# Create your views here.

def signup(request):
  # if the request method is "POST", then
  if request.method == 'POST':
      form = UserCreationForm(request.POST)
      if form.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password1')
        user = User.objects.create_user(username=username, password=password)
        user.save()
        login(request, user)
        return redirect("home")
  else:
    form = UserCreationForm()

  context = {"form":form}
  return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import Receipts, Accounts, Categories

class ReceiptsListView(LoginRequiredMixin, ListView):
  model = Receipts
  template_name = 'receipts/list.html'


class ReceiptsCreateView(CreateView):
  model = Receipts
  template_name = 'receipts/create.html'
  fields = ['vendor', 'total', 'tax', 'date', 'category', 'account']
  success_url = reverse_lazy("receipt_list")

  def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class AccountsListView(ListView):
  model = Accounts
  template_name = 'accounts/list.html'


class AccountsCreateView(CreateView):
  model = Accounts
  template_name = 'accounts/create.html'
  fields = ['name', 'number']
  success_url = reverse_lazy("accounts_list")

  def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class CategoriesListView(ListView):
  model = Categories
  template_name = 'expense_categories/list.html'


class CategoriesCreateView(CreateView):
  model = Categories
  template_name = 'expense_categories/create.html'
  fields = ['name']
  success_url = reverse_lazy("expense_categories_list")

  def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
<main class="narrow-form">
  <h1>Create Account</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<main>
  <h1>Accounts</h1>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Account number</th>
        </tr>
      </thead>
      <tbody>
        <tr>
        {% for account in accounts_list %}
        <td>{{ account.name }}</td>
        <td>{{ account.account_num }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>
{% endblock content %}

receipts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
  </head>
  <body>
    <header>
      <nav>
        <ul class='navigation'>
          {% if user.is_authenticated %}
          <li class='nav-item'><a href="{% url 'receipt_list' %}">Receipts</a></li>
          <li class='nav-item'><a href="{% url 'receipt_create' %}">Create receipt</a></li>
          <li class='nav-item'><a href="{% url 'accounts_list' %}">Accounts</a></li>
          <li class='nav-item'><a href="{% url 'accounts_create' %}">Create account</a></li>
          <li class='nav-item'><a href="{% url 'expense_categories_list' %}">Categories</a></li>
          <li class='nav-item'><a href="{% url 'expense_categories_create' %}">Create category</a></li>
          <li class='nav-item'><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li class='nav-item'><a href="{% url 'login' %}">Login</a></li>
          <li class='nav-item'><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
    {% block content %}{% endblock content %}
  </body>
</html>

receipts/templates/expense_categories/create.html
{% extends 'base.html' %} {% block content %}
<main class="narrow-form">
  <h1>Create Category</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

receipts/templates/expense_categories/list.html
{% extends 'base.html' %}

{% block content %}
<main>
  <h1>Categories</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        {% for category in categories_list %}
        <td>{{ category.name }}</td>
      </tr>
      {% endfor %}
  </tbody>
</table>
</main>

{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
<main class="narrow-form">
  <h1>Create Reciept</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %} {% load static %}

{% block content %}
<main>
  <h1>Receipts</h1>
    <table>
      <thead>
        <tr>
          <th>Vendor</th>
          <th>Total</th>
          <th>Tax</th>
          <th>Date</th>
          <th>Category</th>
          <th>Account</th>
        </tr>
      </thead>
      <tbody>
      {% for receipt in receipts_list %}
      <tr>
        <td>{{ receipt.vendor }}</td>
        <td>{{ receipt.total }}</td>
        <td>{{ receipt.tax }}</td>
        <td>{{ receipt.date | date:"M d, Y" }}</td>
        <td>{{ receipt.category }}</td>
        <td>{{ receipt.account }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>
{% endblock content %}